"""add_word_sounds_table

Revision ID: 95ad89974431
Revises: 
Create Date: 2025-06-19 11:46:36.441746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ad89974431'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_sounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kazakh_word_id', sa.Integer(), nullable=False),
    sa.Column('sound_path', sa.String(length=500), nullable=False),
    sa.Column('sound_url', sa.String(length=500), nullable=True),
    sa.Column('sound_type', sa.String(length=50), nullable=True),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kazakh_word_id'], ['kazakh_words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_word_sounds_word', 'word_sounds', ['kazakh_word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_word_sounds_word', table_name='word_sounds')
    op.drop_table('word_sounds')
    # ### end Alembic commands ###
